### ISSUE TITLE
[number_of_times_each_philosopher_must_eat] argument isn't working in the bonuses

### ISSUE THREAD

**Issue by Floperatok** [Arawyn42/42_philosophers#1]
The last optional argument is not working well in your **bonus part**.
If this argument is specified, the program is supposed to stop when each philosophers ate enough times. However, your program stops if only one **philo** ate the number of time specified.

Exemple:
**Input:**
```./philo_bonus 2 300 100 100 3```
**Output** 
```
1	1 has taken a fork
1	1 has taken a fork
1	1 is eating
101	1 is sleeping
101	2 has taken a fork
101	2 has taken a fork
101	2 is eating
201	1 is thinking
201	1 has taken a fork
201	1 has taken a fork
201	1 is eating
201	2 is sleeping
301	2 is thinking
301	2 has taken a fork
301	1 is sleeping
301	2 has taken a fork
301	2 is eating
401	2 is sleeping
401	1 is thinking
401	1 has taken a fork
401	1 has taken a fork
401	1 is eating
```
As you can see the program stops too early, and only the first **philo** ate 3 times.

**Comment by Arawyn42** [comment]
Thanks for your comment! Now all philosophers should correctly eat until they all finished.
